apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafbat-ui
  namespace: order-inventory
spec:
  project: default

  source:
    repoURL: https://kafbat.github.io/helm-charts
    chart: kafka-ui
    targetRevision: "*"

    helm:
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: yaml
                bootstrapServers: kafka-kafka-bootstrap.order-inventory.svc:9092

          auth:
            type: disabled

          management:
            health:
              ldap:
                enabled: false

        service:
          type: ClusterIP
          port: 8080

  destination:
    server: https://kubernetes.default.svc
    namespace: order-inventory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true