apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: order-inventory
  labels:
    app: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/app
                    operator: In
                    values:
                      - "true"
      containers:
        - name: websocket-service
          image: ghcr.io/racenak/realtime-order-inventory-system/websocket-service:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: HTTP_PORT
              value: "8082"
            - name: OTEL_ENDPOINT
              value: otel-collector:4317
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: order-inventory
  labels:
    app: websocket-service
spec:
  type: ClusterIP
  selector:
    app: websocket-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
