apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-inventory-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: order-inventory
  source:
    repoURL: https://github.com/racenak/Realtime-Order-Inventory-System.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: order-inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
