apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-inventory-databases
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: order-inventory
  source:
    repoURL: https://github.com/racenak/Realtime-Order-Inventory-System.git
    targetRevision: main
    path: k8s/databases
  destination:
    server: https://kubernetes.default.svc
    namespace: order-inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
