apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: order-inventory
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Order Inventory System
  sourceRepos:
    - https://github.com/racenak/Realtime-Order-Inventory-System.git
  destinations:
    - namespace: order-inventory
      server: https://kubernetes.default.svc
    - namespace: order-inventory
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: batch
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: persistentvolumeclaims
      kind: "*"
    - group: argoproj.io
      kind: "*"
  orphanedResources:
    warn: true
